swiftmailer:
    url: '%env(MAILER_URL)%'
    # type memory determina que los emails se enviaran cuando acabe el request por lo que se enviaran automaticamente
    spool: { type: 'memory' }
    
    # Configurar los emails para que se almacenen en "cola" y se envien cuando nosotros queramos
#    spool:
#        # Indicar que sera de tipo file
#        type: file
#        # El path donde guardaremos el fichero
#        path: '%kernel.project_dir%/var/spool'
        
        # Para enviar los emails ejecutaremos este comando en la terminal:
        # php bin/console swiftmailer:spool:send --env=(prod/dev) --message-limit=10 (numero de emails que queremos enviar) 